### ISSUE TITLE
✨ [Feature request]: Update Wiki

### ISSUE THREAD

**Issue by erayalkis** [atapas/react-play#109]
**Is your feature request related to a problem? Please describe.**

I was looking to add documentation for the new PlayMeta component, but I found out very quickly that github doesn't let you create a PR for wiki pages, so I have to do this instead

**Describe the solution you'd like**

Updating Wiki to include documentation for PlayMeta with text from [here](https://github.com/erayalkis/react-play/wiki/PlayMeta#playmeta)
( I will paste the raw text here as a comment if it looks good!)

**Additional context**
Maybe we could start adding propTypes to components for easier readability? 
A propTypes object for PlayMeta would look like this: 
```javascript
PlayMeta.propTypes = {
  id: PropTypes.number, 
  name: PropTypes.string, 
  description: PropTypes.string, 
  path: PropTypes.string, 
  cover: PropTypes.string, 
  component: PropTypes.func 
}
```

**Comment by erayalkis** [comment]
Let me know if I need to make any changes to the text!

**Comment by atapas** [comment]
> > @erayalkis
> > Do you mean you can not access the wiki of this repo and can not create the page directly there?
> 
> Unfortunately, yeah :( It seems that github doesn't let anyone other than the repo owner create wiki pages

What if close the wiki locally, create a page, make update and do a PR?

https://github.com/atapas/react-play.wiki.git

**Comment by atapas** [comment]
> > > @erayalkis
> > > Do you mean you can not access the wiki of this repo and can not create the page directly there?
> > 
> > 
> > Unfortunately, yeah :( It seems that github doesn't let anyone other than the repo owner create wiki pages
> 
> What if clone the wiki locally, create a page, make update and do a PR?
> 
> https://github.com/atapas/react-play.wiki.git
> 
> Let me know if that is possible?

Ok good news :)

![image](https://user-images.githubusercontent.com/3633137/165578125-f98e8c0f-96f3-482f-8f89-46b01218abb9.png)

Now see if you are able to edit.

**Comment by atapas** [comment]
> > > > @erayalkis
> > > > Do you mean you can not access the wiki of this repo and can not create the page directly there?
> > > 
> > > 
> > > Unfortunately, yeah :( It seems that github doesn't let anyone other than the repo owner create wiki pages
> > 
> > 
> > What if clone the wiki locally, create a page, make update and do a PR?
> > https://github.com/atapas/react-play.wiki.git
> > Let me know if that is possible?
> 
> Ok good news :)
> 
> ![image](https://user-images.githubusercontent.com/3633137/165578125-f98e8c0f-96f3-482f-8f89-46b01218abb9.png)
> 
> Now see if you are able to edit.

I have also sent you the collaborator request.

**Comment by erayalkis** [comment]
> > > > @erayalkis
> > > > Do you mean you can not access the wiki of this repo and can not create the page directly there?
> > > 
> > > 
> > > Unfortunately, yeah :( It seems that github doesn't let anyone other than the repo owner create wiki pages
> > 
> > 
> > What if clone the wiki locally, create a page, make update and do a PR?
> > https://github.com/atapas/react-play.wiki.git
> > Let me know if that is possible?
> 
> Ok good news :)
> 
> ![image](https://user-images.githubusercontent.com/3633137/165578125-f98e8c0f-96f3-482f-8f89-46b01218abb9.png)
> 
> Now see if you are able to edit.

Ah, that's perfect! Github normally doesn't let people open PR's for wiki pages. This works perfectly! I'll add a wiki page for PlayMeta ASAP!

**Comment by erayalkis** [comment]
Created the wiki page for PlayMeta! 👍 Let me know if I need to make any changes!

**Comment by atapas** [comment]
> Created the wiki page for PlayMeta! 👍 Let me know if I need to make any changes!

Great, some explanation of this will be helpful

```js
 "reactSnap": {
    "puppeteerArgs": [
      "--no-sandbox",
      "--disable-setuid-sandbox"
    ]
  },
```

**Comment by erayalkis** [comment]
Created a separate wiki page for react-snap as we might need to add extra configurations and documentations later on, let me know if I need to change anything!

**Comment by atapas** [comment]
Looks good. Thanks a lot. I am closing the issue.
