### ISSUE TITLE
🐛 [Bug report]: Content overflow of tag list

### ISSUE THREAD

**Issue by AhnafAhamed** [atapas/react-play#122]
When there are more than 5 tags in the play page the content overflows in screens with width less than 435px

1. Go to [https://www.reactplay.io/plays/expanding-cards](https://www.reactplay.io/plays/expanding-cards)
2. Open dev tools and minimize screen to 435 or less

The tags are expected to wrap up when content starts to overflow.

**Screenshots**
![image](https://user-images.githubusercontent.com/42427928/166117548-5affd4ff-8690-49e6-8f6c-5366f48ccef2.png)

I would love to work on this bug. Thanks

**Comment by atapas** [comment]
Sure, you can take it up.
