### ISSUE TITLE
✨ [Feature request]: Design the play not found page

### ISSUE THREAD

**Issue by vasantisuthar** [atapas/react-play#126]
**Is your feature request related to a problem? Please describe.**
The play not found page is not so designed, and there should also a button to navigate to all plays.

**Describe the solution you'd like**
Design the play not found page when didn't find any play and make it attractive.

**Describe alternatives you've considered**
Also add button to the page to navigate to all plays.

If this needs to be added, then I would like to work on this issue.

**Comment by atapas** [comment]
Yes plz go ahead
