### ISSUE TITLE
🐛 Clear Search and Filter when switching between pages

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#14]
**Describe the bug**
Clear Search and Filter when switching between plages.

**To Reproduce**
- From the landing page search/filter a play
- Now click on a play to go to the play details. See the search is still retained.
- It should be created. If you hit the back button of the browser, it still shows the searched/filtered list. Not the original list of play.

**Expected behavior**
Clear the search and filter when we go from the play listing to the play details page(on route change).

**Screenshots**
None

**Additional context**
Please reach out to @atapas if any clarifications needed.

**Comment by shrilakshmishastry** [comment]
Hi @atapas , I have a fix for this issue .

**Comment by atapas** [comment]
@shrilakshmishastry all yours

**Comment by shrilakshmishastry** [comment]
Thank you

**Comment by atapas** [comment]
@all-contributors please add @shrilakshmishastry  for Code
