### ISSUE TITLE
[Bug]: The puppeteer error while building

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#141]
### Discussed in https://github.com/atapas/react-play/discussions/112

<div type='discussions-op-text'>

<sup>Originally posted by **atapas** April 28, 2022</sup>
@erayalkis 

I am seeing this intermittent error in the log and it fails the build. Do you think, we have a fix for it? Starting this discussion, if you want to get to a root-cause, welcome. When you have a fix, let's convert this one to an issue.

![image](https://user-images.githubusercontent.com/3633137/165795580-af759258-2e9f-4473-a72c-ff71cfb2c475.png)
</div>

**Comment by erayalkis** [comment]
I'll get on it ASAP, thank you for opening an issue for it!

**Comment by atapas** [comment]
@erayalkis One doubt I got so clarifying. A play creator can add play cover in 3 ways.

1.  They provide a link to an online image in the play metadata while creating the play.
1.  They drop a cover.png in the play folder.
1.  They don't provide anything and framework add one default image.

I know in the case of 2 and 3 the social share of the play displays the cover image correctly on all the platforms. Have we taken care of the first case too in the code?

**Comment by erayalkis** [comment]
> @erayalkis One doubt I got so clarifying. A play creator can add play cover in 3 ways.
> 
> 1. They provide a link to an online image in the play metadata while creating the play.
> 2. They drop a cover.png in the play folder.
> 3. They don't provide anything and framework add one default image.
> 
> I know in the case of 2 and 3 the social share of the play displays the cover image correctly on all the platforms. Have we taken care of the first case too in the code?

Yep! The first case should work fine as well, but if I missed an edge case I'll create a PR to fix it ASAP!

**Comment by erayalkis** [comment]
If the new changes don't fix the error, I've read that downgrading react-snap usually fixes the error, so we could also try that!
