### ISSUE TITLE
🐛 [Bug report]: Cancel button text

### ISSUE THREAD

**Issue by abhikhatri67** [atapas/react-play#157]
**Description**
The cancel button text is not visible.

Steps to reproduce the behaviour:
1. Go to '/plays
2. Click on filter plays
3. See an error on filter modal

**Expected behaviour**
Cancel button text

**Screenshots**
<img width="1418" alt="Screenshot 2022-05-07 at 8 33 47 PM" src="https://user-images.githubusercontent.com/15958423/167260147-40d142e6-29d6-411e-a3fe-445bc714565c.png">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome

**Comment by ashutoshdhande** [comment]
@atapas This [Pull request](https://github.com/atapas/react-play/pull/158) tries to fix this issue. Is it satisfactory or any changes needed?

**Comment by Santosh1176** [comment]
Hi, if this is still open issue? I would like to go for it.

**Comment by atapas** [comment]
> @atapas This [Pull request](https://github.com/atapas/react-play/pull/158) tries to fix this issue. Is it satisfactory or any changes needed?

I have added @nirmalkc as a reviewer.
