### ISSUE TITLE
✨ [Feature request]: Filter Plays by Language

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#161]
**Is your feature request related to a problem? Please describe.**
As we support both JS and TS BASED plays, provide ability to filter based on language.

**Describe the solution you'd like**
Add one more filter option for language with the existing filters.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by hasnainmakada-99** [comment]
Tapas sir can you tell me in which file we have to implement this functionality ?

**Comment by atapas** [comment]
> Tapas sir can you tell me in which file we have to implement this functionality ?

I can but you first debug to find out urself and you will learn. I'm there always to tell you at the end 🙌

**Comment by hasnainmakada-99** [comment]
Ok sir let me look into the code

**Comment by hasnainmakada-99** [comment]
@atapas sir, I've looked into the code base and there are going to be many changes if we want to implement this functionality, there should be someone who knows react very well, because I can understand the issue but I will not be able to implement it in react

**Comment by atapas** [comment]
> @atapas sir, I've looked into the code base and there are going to be many changes if we want to implement this functionality, there should be someone who knows react very well, because I can understand the issue but I will not be able to implement it in react

No worries @hasnainmakada-99 

I shall take it up and fix it today. Please feel free to ask me questions based on the fix. I will be happy to answer so that you will also be aware of that portion of the code area.

**Comment by hasnainmakada-99** [comment]
Sure @atapas sir

**Comment by atapas** [comment]
> hasnainmakada-99

Here you go: https://github.com/atapas/react-play/pull/182#issuecomment-1127329853
