### ISSUE TITLE
🐛 [Bug report]: Cancel button on share social medial modal is invisible

### ISSUE THREAD

**Issue by koustov** [atapas/react-play#177]
**Describe the bug**
The cancel button text on **share** modal is not visible by default. On hover the transition is proper

**To Reproduce**
1. Go to 'Share'

**Expected behavior**
Primary button to be placed

**Screenshots**
Taken from production deployment 
![image](https://user-images.githubusercontent.com/7145967/168490592-f9887aa5-4630-437c-a979-d05c0bdcf5ac.png)

**Comment by atapas** [comment]
@koustov Thanks for opening this one. There is an existing issue tracking it already.

https://github.com/atapas/react-play/issues/157

Hence closing it.
