### ISSUE TITLE
[Add a Play]: GitHub Search Site

### ISSUE THREAD

**Issue by Programming-School-Pro-Coding** [atapas/react-play#186]
Thank You! 

## What's the Play about?
GitHub Search user

**Comment by Programming-School-Pro-Coding** [comment]
@atapas link it

**Comment by atapas** [comment]
Please set a proper title for the issue. It just says react-play.

Also please link the PR from the right side setting

![image](https://user-images.githubusercontent.com/3633137/168597551-d1f372a1-3de8-472e-a920-3a20e65da659.png)

**Comment by Programming-School-Pro-Coding** [comment]
> Please set a proper title for the issue. It just says react-play.
> 
> Also please link the PR from the right side setting
> 
> ![image](https://user-images.githubusercontent.com/3633137/168597551-d1f372a1-3de8-472e-a920-3a20e65da659.png)

I don't know how to link it because i don't have a role

![image](https://user-images.githubusercontent.com/96921717/168598037-f3d1834b-0640-4806-b1d1-6d6b3079feac.png)

**Comment by Programming-School-Pro-Coding** [comment]
@atapas you linked this: 
![image](https://user-images.githubusercontent.com/96921717/168598456-9cb5738d-1257-4e2c-80c7-37d853761876.png)

**Comment by Programming-School-Pro-Coding** [comment]
#172
