### ISSUE TITLE
✨ [Feature request]: Close modal on click or esc pressed

### ISSUE THREAD

**Issue by Olaleye-Blessing** [atapas/react-play#195]
**Is your feature request related to a problem? Please describe.**
The filter modal should be closed when `Esc` button is pressed or when the modal container is clicked.

**Describe the solution you'd like**
Event listener should be placed on the `Esc` button and on the modal container.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by atapas** [comment]
Do you want to work on it @Olaleye-Blessing ?

**Comment by Shriom-Trivedi** [comment]
Hi @atapas  if no one is working on this I would love to give it a try

**Comment by Olaleye-Blessing** [comment]
yea but you can give it to @Shriom-Trivedi

**Comment by atapas** [comment]
> Hi @atapas if no one is working on this I would love to give it a try

FCFS, assigned

**Comment by atapas** [comment]
> yea but you can give it to @Shriom-Trivedi

Done. You can review the PR when ready 🙌

**Comment by Shriom-Trivedi** [comment]
@Olaleye-Blessing I've made a PR can you please review it.
