### ISSUE TITLE
[Add a Play]: A simple calendar app to add, update, and delete events.

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#199]
Thank You! 

## What's the Play about?

A simple calendar app to add, update, and delete events.

## Are you willing to take it up for implementation?

NO, @vincentBCP

**Comment by vincentBCP** [comment]
> Thank You!
> 
> ## What's the Play about?
> A simple calendar app, inspired by google calendar, to manage events. This is only saving the events in application state.
> 
> ## What ReactJS concept will be used to create this play?
> Hooks, Context, State Management
>
> ## Are you willing to take it up for implementation?
> NO, @vincentBCP
