### ISSUE TITLE
✨ [Feature request]: Allow selection of preferred styling language

### ISSUE THREAD

**Issue by koustov** [atapas/react-play#205]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
The command line input during play creation should allow the user to select their own choice of styling language (i.e.: CSS/SCSS) and accordingly a template file needs to be placed under the play directory.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by atapas** [comment]
@naiknareshh 

Thanks for starting on it. Could you please post a comment here so that, I can assign it to you?

**Comment by naiknareshh** [comment]
Hey @atapas, yes please assign this to me
