### ISSUE TITLE
✨ [Feature request]: Automatically updating play readme based on user input

### ISSUE THREAD

**Issue by koustov** [atapas/react-play#207]
**Is your feature request related to a problem? Please describe.**
Not a problem

**Describe the solution you'd like**
The idea of this issue is to create a boilerplate readme for every play automatically.

A possible readme template (Unrelated section should be removed)

---

## play-name
detailed play description

## Play Demographic
Language: <language used>
Level : <level>

## Creator Information
User: <username>
Gihub Link: <user github link>
Blog: <blog link>
Video: <video link>

## Implementation Details
Update your implementation idea and details here

## Consideration
Update all considerations(if any)

## Resources
Update external resources(if any)

---
For further suggestion/details, initiate a thread under [discussion](https://github.com/atapas/react-play/discussions)

**Describe alternatives you've considered**
NA

**Additional context**
#200

**Comment by atapas** [comment]
@naiknareshh

Please post a comment here so that I can assign it to you.

**Comment by naiknareshh** [comment]
@atapas Yes, Please assign this to me
