### ISSUE TITLE
🐛 [Bug report]: XML Sitemap is not linked in robots.txt file and other SEO issues

### ISSUE THREAD

**Issue by Sachin-chaurasiya** [atapas/react-play#212]
**Describe the bug**

We have XML sitemap files but there is no reference to it in the robots.txt file, this will affect our project indexing in google or other search engines.

**To Reproduce**

**Expected behavior**
XML sitemap file should have a reference to robots.txt file

**Screenshots**

<img width="762" alt="image" src="https://user-images.githubusercontent.com/59080942/169646596-46c28beb-fd45-45f6-92dc-37c5a1142470.png">

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Sachin-chaurasiya** [comment]
@atapas , I would like to work on this issue.

**Comment by Sachin-chaurasiya** [comment]
Just verify the sitemap.xml file is also missing, we should also add that.
Getting 404 for https://www.reactplay.io/sitemap.xml.

**Comment by Sachin-chaurasiya** [comment]
Open Graph Protocol issues.

<img width="788" alt="image" src="https://user-images.githubusercontent.com/59080942/169647403-39481517-6522-447f-8e9d-febe5b712927.png">

**Comment by Sachin-chaurasiya** [comment]
Title tag issue
<img width="763" alt="image" src="https://user-images.githubusercontent.com/59080942/169647441-e63f868d-1ffc-49e2-9f46-44f1ba39b4cf.png">

**Comment by atapas** [comment]
@Sachin-chaurasiya Good to see you here. The issue is all yours!

**Comment by Rafat97** [comment]
@Sachin-chaurasiya can you tell me which tool you used for scanning those issue?

**Comment by Sachin-chaurasiya** [comment]
> @Sachin-chaurasiya can you tell me which tool you used for scanning those seo issue?

Sure, I used [woorank](https://www.woorank.com/) for a quick scan.
