### ISSUE TITLE
✨ [Feature request]: Add TypeScript Support

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#29]
Currently the `yarn create-play` command creates the play in JavaScript(JSX). Please add the support to create play scaffolding based on TypeScript.

**Comment by koustov** [comment]
@atapas  may i take this one?

**Comment by koustov** [comment]
@atapas 

Let me know if this make sense
![image](https://user-images.githubusercontent.com/7145967/164988849-bbd49ec1-9797-47bb-84a8-8e0f2619dc07.png)

![image](https://user-images.githubusercontent.com/7145967/164988933-57713d76-494f-4051-a394-5c5a8c65d6e7.png)

**Comment by atapas** [comment]
> @atapas @nirmalkc
> 
> Let me know if this make sense. A tiny UI update: ![image](https://user-images.githubusercontent.com/7145967/164988849-bbd49ec1-9797-47bb-84a8-8e0f2619dc07.png)
> 
> Plop option: ![image](https://user-images.githubusercontent.com/7145967/164988933-57713d76-494f-4051-a394-5c5a8c65d6e7.png)

Yep, make sense to me.
