### ISSUE TITLE
[Add a play]: Random meme generator

### ISSUE THREAD

**Issue by murtuzaalisurti** [atapas/react-play#37]
I have an idea to add a play which demonstrates the use of APIs to generate random data (it can be anything, quotes, images, memes, etc)

@atapas Let me know if this works!

**Comment by atapas** [comment]
Random meme will be awesome? Want to try that? Go for it. Please edit the issue title accordingly.

**Comment by murtuzaalisurti** [comment]
Yes, random meme generator would be cool!

**Comment by atapas** [comment]
> Yes, random meme generator would be cool!

Super, I have updated the issue title.

**Comment by murtuzaalisurti** [comment]
Hey @atapas I am getting an error while creating a play!

![Screenshot (184)](https://user-images.githubusercontent.com/68743212/163764495-b323c97c-21e1-459a-8675-291a7b0a6c44.png)

**Comment by atapas** [comment]
That's Weird. Let me take a look.

**Comment by atapas** [comment]
> Hey @atapas I am getting an error while creating a play!
> 
> ![Screenshot (184)](https://user-images.githubusercontent.com/68743212/163764495-b323c97c-21e1-459a-8675-291a7b0a6c44.png)

I just tried it with the same value and it worked. Could you please try it once with Git Bash Terminal?

![image](https://user-images.githubusercontent.com/3633137/163767970-762dcfdf-5074-439e-984a-2424b18ab044.png)


I'm suspecting some input it not going well with the VS Code terminal setting. PLease let me know @murtuzaalisurti

**Comment by atapas** [comment]
For me worked with VS Code too.. Please let me know if it went well with Git bash/command prompt for you?

![image](https://user-images.githubusercontent.com/3633137/163768483-2d77faa9-0418-460e-affb-b555e52ba5c9.png)

**Comment by murtuzaalisurti** [comment]
> For me worked with VS Code too.. Please let me know if it went well with Git bash/command prompt for you?
> 
> ![image](https://user-images.githubusercontent.com/3633137/163768483-2d77faa9-0418-460e-affb-b555e52ba5c9.png)


Getting the error in git bash too!


![mintty_4OQgXiZ6HW](https://user-images.githubusercontent.com/68743212/163777209-d1c932dc-ca8a-4f9e-810a-7f02d56feb2a.jpg)


> It says, `replaceAll is not a function`

**Comment by atapas** [comment]
What's the Node, Yarn version?

**Comment by murtuzaalisurti** [comment]
@atapas yarn 1.22.17

**Comment by murtuzaalisurti** [comment]
updated yarn but still the same issue!

**Comment by atapas** [comment]
> updated yarn but still the same issue!

That's really strange! Want to get on a quick call now? Can check it out.

**Comment by murtuzaalisurti** [comment]
yeah sure!
@atapas

**Comment by atapas** [comment]
> yeah sure! @atapas

Pnged you on Twitter @murtuzaalisurti

**Comment by murtuzaalisurti** [comment]
@atapas I used a recent version of node and it didn't work in administrator cmd! So, there's an issue with node.

**Comment by murtuzaalisurti** [comment]
It might be that the function or expression is deprecated, or something like that.

**Comment by atapas** [comment]
> @atapas I used a recent version of node and it didn't work in administrator cmd! So, there's an issue with node.

So with which version of node it finally worked?

**Comment by murtuzaalisurti** [comment]
> > @atapas I used a recent version of node and it didn't work in administrator cmd! So, there's an issue with node.
> 
> So with which version of node it finally worked?

16.14.0

**Comment by atapas** [comment]
> > > @atapas I used a recent version of node and it didn't work in administrator cmd! So, there's an issue with node.
> > 
> > 
> > So with which version of node it finally worked?
> 
> 16.14.0

We need to document that. Please create an issue.

**Comment by murtuzaalisurti** [comment]
> > > > @atapas I used a recent version of node and it didn't work in administrator cmd! So, there's an issue with node.
> > > 
> > > 
> > > So with which version of node it finally worked?
> > 
> > 
> > 16.14.0
> 
> We need to document that. Please create an issue.

Sure, will create an issue!
