### ISSUE TITLE
✨ [Feature request]: Add shimmer effect for the play thumbnails

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#38]
**Is your feature request related to a problem? Please describe.**
On the first load the images takes some time to get added to the DOM. We can use shimmer effect to make it look more pleasant.

**Describe the solution you'd like**
We can create our own Image component with a shimmer as  a fallback or use any well reputated NPM package that does it well.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by abhikhatri67** [comment]
Hi @atapas,

Should I try this one?

**Comment by atapas** [comment]
> Hi @atapas,
> 
> Should I try this one?

All yours now.
