### ISSUE TITLE
✨ [Feature request]: Show no play found when there is no match for filter and search result 

### ISSUE THREAD

**Issue by shrilakshmishastry** [atapas/react-play#43]
## Need a feature that shows no play found when there is no match in filter and search result. 

Currently, the screen is blank when there is no match found. It would be a good experience if there is some message showing no play match for the applied filter or search

**Comment by hasnainmakada-99** [comment]
Tapas sir, I would like to work on this issue

**Comment by atapas** [comment]
> Tapas sir, I would like to work on this issue

Ok sure. For design of the page please work with @nirmalkc

**Comment by atapas** [comment]
@nirmalkc the code logic is done and in main. Could you please create a branch and style this one? I shall close the issue after that.

**Comment by atapas** [comment]
Styling will be done part of #126
