### ISSUE TITLE
[Add a Play]: State of Component

### ISSUE THREAD

**Issue by Abhishek-90** [atapas/react-play#44]
Thank You! 

## What's the Play about?
It will tell about the state of react Components, what happens when you change a state in a functional component

## What ReactJS concept will be used to create this play?
hooks, state management, state

## Are you willing to take it up for implementation?
Yes

**Comment by Abhishek-90** [comment]
#41

**Comment by atapas** [comment]
@Abhishek-90 Please let me know when it is ready to review?

**Comment by Abhishek-90** [comment]
@atapas you can review it now. Please let me know if it requires any changes/enhancement

**Comment by atapas** [comment]
> @atapas you can review it now. Please let me know if it requires any changes/enhancement

Done with the review. Please take a look. Also, there are merge conflicts in these two files. Please resolve this carefully.

![image](https://user-images.githubusercontent.com/3633137/163809515-3ca0c2e2-5d4f-4f65-9c1c-0b58cecc7279.png)
