### ISSUE TITLE
✨ [Feature request]: Generate a Readme.md file for each play

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#47]
**Is your feature request related to a problem? Please describe.**
Each of the play can have its own documentation to tell what it is about, some code level details. So generate a Readme.md file as part of the play creation process.

**Describe the solution you'd like**
Create a automatic Readme file per play

**Describe alternatives you've considered**
Alternative is creating the read me manually

**Additional context**
None

**Comment by hasnainmakada-99** [comment]
Tapas sir, I would love to work on this issue

**Comment by atapas** [comment]
All yours @hasnainmakada-99

**Comment by hasnainmakada-99** [comment]
Thank you sir

**Comment by atapas** [comment]
See Also: https://github.com/atapas/react-play/discussions/55

**Comment by atapas** [comment]
@all-contributors please add @hasnainmakada-99  for Code
