### ISSUE TITLE
✨ [Feature request]: Create a list of Play ideas

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#48]
**Is your feature request related to a problem? Please describe.**
Create a page with a list of play ideas and categorize them by levels(Beginner, Intermediate, Advanced). It will help anyone to look into the list and create a play based on it.

**Describe the solution you'd like**
A separate page that lists all the play ideas wth descriptions.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by nirmalkc** [comment]
### Action Items

- [ ] Homepage mockup showing the link/anchor to take the user to the ideas page
- [ ] Ideas page mockup - a page that lists all the ideas together. Every idea can have a button to let the users to start with that idea
- [ ] Mockups showing filtering options
- [ ] Markups & styling for all the above mentioned items
