### ISSUE TITLE
🐛 [Bug report]: Deep Linking for the Plays fails. It shows a blank page.

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#66]
**Describe the bug**
If you hit any play URL directly, it gives a blank page. It should show the play details page.

**To Reproduce**
1. Open your browser
2. Paste this URL: https://www.reactplay.io/plays/social-card and hit enter
3. You will see a blank screen
4. Error in the browser console

![image](https://user-images.githubusercontent.com/3633137/164027452-948f2dda-862a-4d62-af07-7a556f056c3e.png)

**Expected behavior**
The Play should be accessible with deep linking

**Screenshots**

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
 All

**Additional context**
Moving to play detail from the play list works well.

**Comment by 6km** [comment]
I have worked on a fix for this issue. I will open a PR.
