### ISSUE TITLE
✨ [Feature request]: Change meta information based on the route

### ISSUE THREAD

**Issue by atapas** [atapas/react-play#76]
**Is your feature request related to a problem? Please describe.**
What we share a play with its deep link URL, it takes the Reactplay platform's meta(og, Twitter) image, title, and description. Rather, it should display the cover image, title, and description of the play that we are sharing on social media.

**Describe the solution you'd like**
I do not have a solution proposed yet but the contributor can start a discussion with me to brainstorm.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by erayalkis** [comment]
Maybe we could create a PlayMeta component that takes in an object of meta values?
So for example we could create a meta object in each Play component like this:
```javascript
const meta = {
    title: 'Example Meta Title',
    description: 'I am an example description',
 }
```
And then we can just destructure this object and pass it into the PlayMeta component:
```javascript
  <PlayMeta {...meta} />
```

**Comment by atapas** [comment]
> Maybe we could create a PlayMeta component that takes in an object of meta values? So for example we could create a meta object in each Play component like this:
> 
> ```js
> const meta = {
>     title: 'Example Meta Title',
>     description: 'I am an example description',
>  }
> ```
> 
> And then we can just destructure this object and pass it into the PlayMeta component:
> 
> ```js
>   <PlayMeta {...meta} />
> ```

I think it is a good idea. I have taken the same solution for my website which is built using Next.js. @erayalkis do you want to take it up and get a PR ready? We can start collaborating on reviews there.

**Comment by erayalkis** [comment]
Sure, I'd love to! I'll start working on it ASAP!
