### ISSUE TITLE
🐛 [Bug report]: Responsive Design for State Play

### ISSUE THREAD

**Issue by Abhishek-90** [atapas/react-play#83]
**Describe the bug**
State play needs to have a cover and it is should be responsive.

**Expected behavior**
Play should have responsive design for desktop and small devices alike

**Comment by atapas** [comment]
@Abhishek-90 Could you please provide a title to this issue?

**Comment by Abhishek-90** [comment]
@atapas by tomorrow & yes, It will include cover image
