### ISSUE TITLE
Quizeo App

### ISSUE THREAD

**Issue by vasantisuthar** [atapas/react-play#97]
Thank You! 

## What's the Play about?
A react application of quizzes about favorite movies and series.

## What ReactJS concept will be used to create this play?
Hooks, react-redux, reselect, and react-router

## Are you willing to take it up for implementation?
yes

**Comment by vasantisuthar** [comment]
I had set up the project but got this error, I tried but was not able to solve this.
Uncaught (in promise) Error: The message port closed before a response was received.

**Comment by vasantisuthar** [comment]
<img width="960" alt="2022-04-29" src="https://user-images.githubusercontent.com/63599802/165942900-9a3e24d4-b3f8-48a0-9f71-c43b41d43690.png">

When I click on one of the images it gives a 404 status and the above error, rest npm is successfully installed and started also.

**Comment by atapas** [comment]
> <img alt="2022-04-29" width="960" src="https://user-images.githubusercontent.com/63599802/165942900-9a3e24d4-b3f8-48a0-9f71-c43b41d43690.png">
> 
> When I click on one of the images it gives a 404 status and the above error, rest npm is successfully installed and started also.

Ok so the problem is with code then, not the environment. Could you please create the PR so that can take a look at the code changes and suggest!
